export type RazzleContainerWidgetType = 'row' | 'column' | 'container'
export type RazzleWidgetType =
  | 'text'
  | 'image'
  | 'list'
  | 'list-item'
  | 'custom-list'
  | 'custom-list-item'
  | 'link'
  | 'table'
  | 'table-column'
  | 'custom-table'
  | 'custom-table-column'
  | 'custom-table-row'
  | 'custom-table-cell'
  | 'selectable'
  | RazzleContainerWidgetType
