version: '3.1'

services:
  database:
    image: 'bitnami/mongodb:4.4'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=razzle
      - MONGODB_ROOT_PASSWORD=razzle
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - '27017:27017'
    networks:
      - docker-net

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=razzle
    ports:
      - '6379:6379'

  mongo-express:
    image: mongo-express
    depends_on:
      - database
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: razzle
      ME_CONFIG_MONGODB_ADMINPASSWORD: razzle
      ME_CONFIG_MONGODB_URL: mongodb://razzle:razzle@database:27017/razzle_database?authSource=admin&directConnection=true
    networks:
      - docker-net

networks:
  docker-net:
