/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter:3.0.2")
    api("org.springframework.boot:spring-boot-starter-validation:3.0.2")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.1")
    api("org.json:json:20190722")
    api("com.fasterxml.jackson.core:jackson-databind:2.14.1")
    api("org.java-websocket:Java-WebSocket:1.5.3")
    api("org.awaitility:awaitility:4.2.0")
    api("org.projectlombok:lombok:1.18.24")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.2")
}

group = "ai.razzle"
version = "0.3.0-56-SNAPSHOT"
description = "java-sdk"
java.sourceCompatibility = JavaVersion.VERSION_17

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
