name: Release the frontend to staging

on:
  push:
    branches:
      -  release/frontend/prod

env:
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  STAGING_CERTIFICATE_ARN: ${{ secrets.STAGING_CERT_ARN }}
  STAGING_CLOUDFRONT_SSL_CERTIFICATE_ARN: ${{ secrets.STAGING_CLOUDFRONT_ARN }}
  AWS_REGION: eu-west-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Get the commit hashes
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install packages
        id: install-packages
        run: npm install

      - name: Generate prisma client
        id: generate-prisma-client
        run: npx nx run backend:migrate-generate

      - name: Build the frontend for production target
        id: build-production
        run: npx nx run frontend:build:production

      - name: Deploy
        run: aws s3 sync ./dist/apps/frontend s3://app.getrazzle.com

      - name: Invalid caches
        env:
          DISTRIBUTION: ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
        uses: chetan/invalidate-cloudfront-action@v2
